# Generated by Django 5.1.2 on 2024-12-18 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tur ',
                'verbose_name_plural': 'Turlar',
            },
        ),
        migrations.CreateModel(
            name='Gullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Maqola nomi')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Maqola matni')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post/photos/', verbose_name='Rasmi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.turlar', verbose_name='Kategororiyasi')),
            ],
            options={
                'verbose_name': 'Gul ',
                'verbose_name_plural': 'Gullar',
                'ordering': ['-created'],
            },
        ),
    ]
